### PR TITLE
Fix issues detected by linter

### LINKED ISSUE #26: Loop is terminated unconditionally
https://github.com/egnyte/ax/blob/756ae1ddde1dad0b7525cace45fa9e6ef69d67da/pkg/config/cloudwatch.go#L40-L49

https://github.com/egnyte/ax/blob/756ae1ddde1dad0b7525cace45fa9e6ef69d67da/pkg/config/stackdriver.go#L39-L48

Caught by `staticcheck`.

### PR DESCRIPTION
**Pull request by romanlevin**
All of these were detected using `staticcheck` and `megachecker`.

Fixes #26 and some other things.

### CODE REVIEW

File: pkg/config/cloudwatch.go [hunk 1]
```diff
@@ -7,12 +7,6 @@ import (
 	"github.com/egnyte/ax/pkg/backend/cloudwatch"
 )
 
-func testCloudWatch(em EnvMap) bool {
-	cwClient := cloudwatch.New(em["accesskey"], em["accesssecretkey"], em["region"], "")
-	_, err := cwClient.ListGroups()
-	return err != nil
-}
```
Comment (romanlevin) [inline pkg/config/cloudwatch.go]: @zefhemel You seem to have these for all the backends, but they don't seem to be used. Am I missing something?

Comment (zefhemel) [reply pkg/config/cloudwatch.go]: Right... no, they can be removed.
